# With CSV

In [1]:
# import data from url 

import requests
import pandas as pd
from io import StringIO

url = "" # paste URL into this
headers = {"User-Agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.14; rv:66.0) Gecko/20100101 Firefox/66.0"}
req = requests.get(url, headers=headers)
data = StringIO(req.text)

pd.read_csv(data)

In [ ]:
# Sep Parameter , to define Seperater
pd.read_csv(sep='\t')

In [ ]:
# Index_col , to make column index
pd.read_csv(index_col= 'Column_name')

In [ ]:
#Name Parameter, to make header
pd.read_csv(names=['names of columns'])

In [ ]:
# Header Parameter , from where you want to start rows
pd.read_csv(header=1)

In [ ]:
# Use_col parameter, Which columns you want to use
pd.read_csv(usecols=['names of columns'])

In [ ]:
# Squeeze PArameter , to make dataframe a series
pd.read_csv(usecols=['names of columns'], squeeze = True)

In [ ]:
# Skip rows/ nrows parameter,  to skip this rows and Nraws = to add this number of rows
pd.read_csv(skiprows=['number of columns (0, 1)'])

In [ ]:
# Encoding parameter, change encoding when you will get UnicodeDecodeError
pd.read_csv(encoding='')

In [ ]:
# Skip bad lines , if all lines have no same values skip with different values
pd.read_csv(error_bad_lines = False)

In [ ]:
# Dtypes parameter, to change data type
pd.read_csv(dtype={'column name':int})

In [ ]:
#Handling Dates, to change date type to date from object
pd.read_csv(parse_dates=['column name'])

In [7]:
# Converters, to convert to short name or other names
def rename(name):
    if name == 'RCB':
        return 'rcb'
    else:
        return 'RCB'
    
rename('RCB')

pd.read_csv(converters={'column-name' : rename})

'rcb'

In [ ]:
# Na_Values Parameter, consider other value as NA

pd.read_csv(na_values=['value name'])

In [ ]:
# Loading Huge data as Chunks, devide big data into chunks, it will devide data in small chunks
df = pd.read_csv(chunksize=5000)

# With JSON

In [ ]:
pd.read_json('file_name or URL name')

# With SQL

In [2]:
pip install mysql.connector

Collecting mysql.connector
  Downloading mysql-connector-2.2.9.tar.gz (11.9 MB)
     ---------------------------------------- 0.0/11.9 MB ? eta -:--:--
     ------- -------------------------------- 2.1/11.9 MB 11.8 MB/s eta 0:00:01
     --------------- ------------------------ 4.7/11.9 MB 11.9 MB/s eta 0:00:01
     ----------------------- ---------------- 7.1/11.9 MB 11.8 MB/s eta 0:00:01
     ------------------------------- -------- 9.4/11.9 MB 11.7 MB/s eta 0:00:01
     --------------------------------------  11.8/11.9 MB 11.7 MB/s eta 0:00:01
     --------------------------------------- 11.9/11.9 MB 11.6 MB/s eta 0:00:00
  Installing build dependencies: started
  Installing build dependencies: finished with status 'done'
  Getting requirements to build wheel: started
  Getting requirements to build wheel: finished with status 'done'
  Preparing metadata (pyproject.toml): started
  Preparing metadata (pyproject.toml): finished with status 'done'
Building wheels for collected packages: mysql.connector
  Building wheel for mysql.connector (pyproject.toml): started
  Building wheel for mysql.connector (pyproject.toml): finished with status 'done'
  Created wheel for mysql.connector: filename=mysql_connector-2.2.9-cp312-cp312-win_amd64.whl size=247960 sha256=06bd4b28efee78d2c1029c7f21fb2b698a061c5d70e47295165d32e9fcc78d5d
  Stored in directory: c:\users\keval\appdata\local\pip\cache\wheels\03\17\fa\d7604c72dd3dd6d3eb3d249abf36cc532c9a9b4354b8f1bc4f
Successfully built mysql.connector
Installing collected packages: mysql.connector
Successfully installed mysql.connector-2.2.9
Note: you may need to restart the kernel to use updated packages.

In [4]:
import mysql.connector

conn = mysql.connector.connect(host = 'localhost', user='root', password='',database='world')

In [5]:
pd.read_sql_query('SELECT * from city',conn)

C:\Users\keval\AppData\Local\Temp\ipykernel_6316\3732836543.py:1: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  pd.read_sql_query('SELECT * from city',conn)

        ID            Name CountryCode       District  Population
0        1           Kabul         AFG          Kabol     1780000
1        2        Qandahar         AFG       Qandahar      237500
2        3           Herat         AFG          Herat      186800
3        4  Mazar-e-Sharif         AFG          Balkh      127800
4        5       Amsterdam         NLD  Noord-Holland      731200
...    ...             ...         ...            ...         ...
4074  4075      Khan Yunis         PSE     Khan Yunis      123175
4075  4076          Hebron         PSE         Hebron      119401
4076  4077        Jabaliya         PSE     North Gaza      113901
4077  4078          Nablus         PSE         Nablus      100231
4078  4079           Rafah         PSE          Rafah       92020

[4079 rows x 5 columns]

# With API

In [6]:
import pandas as pd
import requests

In [14]:
url = "https://api.themoviedb.org/3/tv/top_rated?language=en-US&page=1"

headers = {
    "accept": "application/json",
    "Authorization": "Bearer eyJhbGciOiJIUzI1NiJ9.eyJhdWQiOiIwNzhhY2Y1ZDI0ZTM2ZDBmMDgyMzAyMDVjNGVlMzA0MCIsIm5iZiI6MTcyNTQ0OTk0NC4yOTA1MjQsInN1YiI6IjY2ZDg0NGIwODZmZWMzYWQyODYwNDg5YiIsInNjb3BlcyI6WyJhcGlfcmVhZCJdLCJ2ZXJzaW9uIjoxfQ.dYuKAd731sDkHAJZu-Y1j3eT9OSfSOGf4FbZnfOlk0Q"
}
response =  requests.get(url,headers=headers)

In [16]:
response.json()

{'page': 1,
 'results': [{'adult': False,
   'backdrop_path': '/9faGSFi5jam6pDWGNd0p8JcJgXQ.jpg',
   'genre_ids': [18, 80],
   'id': 1396,
   'origin_country': ['US'],
   'original_language': 'en',
   'original_name': 'Breaking Bad',
   'overview': "Walter White, a New Mexico chemistry teacher, is diagnosed with Stage III cancer and given a prognosis of only two years left to live. He becomes filled with a sense of fearlessness and an unrelenting desire to secure his family's financial future at any cost as he enters the dangerous world of drugs and crime.",
   'popularity': 803.55,
   'poster_path': '/ztkUQFLlC19CCMYHW9o1zWhJRNq.jpg',
   'first_air_date': '2008-01-20',
   'name': 'Breaking Bad',
   'vote_average': 8.913,
   'vote_count': 14109},
  {'adult': False,
   'backdrop_path': '/96RT2A47UdzWlUfvIERFyBsLhL2.jpg',
   'genre_ids': [16, 18, 10759, 10765],
   'id': 209867,
   'origin_country': ['JP'],
   'original_language': 'ja',
   'original_name': '葬送のフリーレン',
   'overview': 'After the party of heroes defeated the Demon King, they restored peace to the land and returned to lives of solitude. Generations pass, and the elven mage Frieren comes face to face with humanity’s mortality. She takes on a new apprentice and promises to fulfill old friends’ dying wishes. Can an elven mind make peace with the nature of life and death? Frieren embarks on her quest to find out.',
   'popularity': 336.506,
   'poster_path': '/dqZENchTd7lp5zht7BdlqM7RBhD.jpg',
   'first_air_date': '2023-09-29',
   'name': "Frieren: Beyond Journey's End",
   'vote_average': 8.884,
   'vote_count': 262},
  {'adult': False,
   'backdrop_path': '/9kyyQXy79YRdY5mhrYKyktbFMev.jpg',
   'genre_ids': [16, 35, 10765],
   'id': 94954,
   'origin_country': ['US'],
   'original_language': 'en',
   'original_name': 'Hazbin Hotel',
   'overview': "In attempt to find a non-violent alternative for reducing Hell's overpopulation, the daughter of Lucifer opens a rehabilitation hotel that offers a group of misfit demons a chance at redemption.",
   'popularity': 241.966,
   'poster_path': '/rXojaQcxVUubPLSrFV8PD4xdjrs.jpg',
   'first_air_date': '2024-01-18',
   'name': 'Hazbin Hotel',
   'vote_average': 8.875,
   'vote_count': 1063},
  {'adult': False,
   'backdrop_path': '/rkB4LyZHo1NHXFEDHl9vSD9r1lI.jpg',
   'genre_ids': [16, 10765, 10759],
   'id': 94605,
   'origin_country': ['US'],
   'original_language': 'en',
   'original_name': 'Arcane',
   'overview': 'Amid the stark discord of twin cities Piltover and Zaun, two sisters fight on rival sides of a war between magic technologies and clashing convictions.',
   'popularity': 185.414,
   'poster_path': '/fqldf2t8ztc9aiwn3k6mlX3tvRT.jpg',
   'first_air_date': '2021-11-06',
   'name': 'Arcane',
   'vote_average': 8.749,
   'vote_count': 3941},
  {'adult': False,
   'backdrop_path': '/kU98MbVVgi72wzceyrEbClZmMFe.jpg',
   'genre_ids': [16, 10759, 10765],
   'id': 246,
   'origin_country': ['US'],
   'original_language': 'en',
   'original_name': 'Avatar: The Last Airbender',
   'overview': 'In a war-torn world of elemental magic, a young boy reawakens to undertake a dangerous mystic quest to fulfill his destiny as the Avatar, and bring peace to the world.',
   'popularity': 132.123,
   'poster_path': '/cHFZA8Tlv03nKTGXhLOYOLtqoSm.jpg',
   'first_air_date': '2005-02-21',
   'name': 'Avatar: The Last Airbender',
   'vote_average': 8.731,
   'vote_count': 4046},
  {'adult': False,
   'backdrop_path': '/2rmK7mnchw9Xr3XdiTFSxTTLXqv.jpg',
   'genre_ids': [10759, 35, 16],
   'id': 37854,
   'origin_country': ['JP'],
   'original_language': 'ja',
   'original_name': 'ワンピース',
   'overview': 'Years ago, the fearsome Pirate King, Gol D. Roger was executed leaving a huge pile of treasure and the famous "One Piece" behind. Whoever claims the "One Piece" will be named the new King of the Pirates.\n\nMonkey D. Luffy, a boy who consumed a "Devil Fruit," decides to follow in the footsteps of his idol, the pirate Shanks, and find the One Piece. It helps, of course, that his body has the properties of rubber and that he\'s surrounded by a bevy of skilled fighters and thieves to help him along the way.\n\nLuffy will do anything to get the One Piece and become King of the Pirates!',
   'popularity': 188.206,
   'poster_path': '/cMD9Ygz11zjJzAovURpO75Qg7rT.jpg',
   'first_air_date': '1999-10-20',
   'name': 'One Piece',
   'vote_average': 8.7,
   'vote_count': 4590},
  {'adult': False,
   'backdrop_path': '/A6tMQAo6t6eRFCPhsrShmxZLqFB.jpg',
   'genre_ids': [10759, 16, 10765, 35],
   'id': 31911,
   'origin_country': ['JP'],
   'original_language': 'ja',
   'original_name': '鋼の錬金術師 FULLMETAL ALCHEMIST',
   'overview': 'Disregard for alchemy’s laws ripped half of Edward Elric’s limbs from his body and left his brother Alphonse’s soul clinging to a suit of armor. To restore what was lost, the brothers seek the Philosopher’s Stone. Enemies and allies – the corrupt military, the Homunculi, and foreign alchemists – will alter the Elric brothers course, but their purpose will remain unchanged and their bond unbreakable.',
   'popularity': 316.754,
   'poster_path': '/8H4ej2NpujYVBPsW2smmzC8d2xU.jpg',
   'first_air_date': '2009-04-05',
   'name': 'Fullmetal Alchemist: Brotherhood',
   'vote_average': 8.698,
   'vote_count': 2006},
  {'adult': False,
   'backdrop_path': '/rBF8wVQN8hTWHspVZBlI3h7HZJ.jpg',
   'genre_ids': [16, 35, 10765, 10759],
   'id': 60625,
   'origin_country': ['US'],
   'original_language': 'en',
   'original_name': 'Rick and Morty',
   'overview': "Rick is a mentally-unbalanced but scientifically gifted old man who has recently reconnected with his family. He spends most of his time involving his young grandson Morty in dangerous, outlandish adventures throughout space and alternate universes. Compounded with Morty's already unstable family life, these events cause Morty much distress at home and school.",
   'popularity': 569.748,
   'poster_path': '/gdIrmf2DdY5mgN6ycVP0XlzKzbE.jpg',
   'first_air_date': '2013-12-02',
   'name': 'Rick and Morty',
   'vote_average': 8.697,
   'vote_count': 9628},
  {'adult': False,
   'backdrop_path': '/7BoRhg8zXP0ca9Zql4p8llCFR2P.jpg',
   'genre_ids': [18, 10765, 35],
   'id': 221851,
   'origin_country': ['KR'],
   'original_language': 'ko',
   'original_name': '내 남편과 결혼해줘',
   'overview': 'Kang Ji-won, a terminally ill cancer patient, is killed by her husband and best friend after she witnesses them having an affair. She wakes up 10 years before the incident and decides to seek revenge with the help of Yu Ji-hyuk, a director at the company where she works. Now, she must reclaim her fate and eliminate the trash from her life.',
   'popularity': 147.348,
   'poster_path': '/y2hvE76S6Me0uhYEQ1P8lGf7Wm0.jpg',
   'first_air_date': '2024-01-01',
   'name': 'Marry My Husband',
   'vote_average': 8.687,
   'vote_count': 393},
  {'adult': False,
   'backdrop_path': '/hPea3Qy5Gd6z4kJLUruBbwAH8Rm.jpg',
   'genre_ids': [80, 18],
   'id': 60059,
   'origin_country': ['US'],
   'original_language': 'en',
   'original_name': 'Better Call Saul',
   'overview': 'Six years before Saul Goodman meets Walter White. We meet him when the man who will become Saul Goodman is known as Jimmy McGill, a small-time lawyer searching for his destiny, and, more immediately, hustling to make ends meet. Working alongside, and, often, against Jimmy, is “fixer” Mike Ehrmantraut. The series tracks Jimmy’s transformation into Saul Goodman, the man who puts “criminal” in “criminal lawyer".',
   'popularity': 1249.211,
   'poster_path': '/fC2HDm5t0kHl7mTm7jxMR31b7by.jpg',
   'first_air_date': '2015-02-08',
   'name': 'Better Call Saul',
   'vote_average': 8.68,
   'vote_count': 5081},
  {'adult': False,
   'backdrop_path': '/900tHlUYUkp7Ol04XFSoAaEIXcT.jpg',
   'genre_ids': [18],
   'id': 87108,
   'origin_country': ['US'],
   'original_language': 'en',
   'original_name': 'Chernobyl',
   'overview': 'The true story of one of the worst man-made catastrophes in history: the catastrophic nuclear accident at Chernobyl. A tale of the brave men and women who sacrificed to save Europe from unimaginable disaster.',
   'popularity': 374.107,
   'poster_path': '/hlLXt2tOPT6RRnjiUmoxyG1LTFi.jpg',
   'first_air_date': '2019-05-06',
   'name': 'Chernobyl',
   'vote_average': 8.676,
   'vote_count': 6175},
  {'adult': False,
   'backdrop_path': '/70YdbMELM4b8x8VXjlubymb2bQ0.jpg',
   'genre_ids': [18, 10751],
   'id': 70785,
   'origin_country': ['CA'],
   'original_language': 'en',
   'original_name': 'Anne with an E',
   'overview': 'A coming-of-age story about an outsider who, against all odds and numerous challenges, fights for love and acceptance and for her place in the world. The series centers on a young orphaned girl in the late 1890’s, who, after an abusive childhood spent in orphanages and the homes of strangers, is mistakenly sent to live with an elderly woman and her aging brother. Over time, 13-year-old Anne will transform their lives and eventually the small town in which they live with her unique spirit, fierce intellect and brilliant imagination.',
   'popularity': 445.068,
   'poster_path': '/6P6tXhjT5tK3qOXzxF9OMLlG7iz.jpg',
   'first_air_date': '2017-03-19',
   'name': 'Anne with an E',
   'vote_average': 8.675,
   'vote_count': 4615},
  {'adult': False,
   'backdrop_path': '/cHyY5z4txdVyGtYMvBJhCqCcJso.jpg',
   'genre_ids': [16, 10765, 18, 10759, 35, 10762],
   'id': 92685,
   'origin_country': ['US'],
   'original_language': 'en',
   'original_name': 'The Owl House',
   'overview': "An animated fantasy-comedy series that follows Luz, a self-assured teenage girl who accidentally stumbles upon a portal to a magical world where she befriends a rebellious witch, Eda, and an adorably tiny warrior, King. Despite not having magical abilities, Luz pursues her dream of becoming a witch by serving as Eda's apprentice at the Owl House and ultimately finds a new family in an unlikely setting.",
   'popularity': 361.153,
   'poster_path': '/zhdy3PcNVE15wj1wrxn45ARZBnx.jpg',
   'first_air_date': '2020-01-10',
   'name': 'The Owl House',
   'vote_average': 8.671,
   'vote_count': 1562},
  {'adult': False,
   'backdrop_path': '/3GQKYh6Trm8pxd2AypovoYQf4Ay.jpg',
   'genre_ids': [16, 10759, 10765],
   'id': 85937,
   'origin_country': ['JP'],
   'original_language': 'ja',
   'original_name': '鬼滅の刃',
   'overview': 'It is the Taisho Period in Japan. Tanjiro, a kindhearted boy who sells charcoal for a living, finds his family slaughtered by a demon. To make matters worse, his younger sister Nezuko, the sole survivor, has been transformed into a demon herself. Though devastated by this grim reality, Tanjiro resolves to become a “demon slayer” so that he can turn his sister back into a human, and kill the demon that massacred his family.',
   'popularity': 143.924,
   'poster_path': '/xUfRZu2mi8jH6SzQEJGP6tjBuYj.jpg',
   'first_air_date': '2019-04-06',
   'name': 'Demon Slayer: Kimetsu no Yaiba',
   'vote_average': 8.661,
   'vote_count': 6358},
  {'adult': False,
   'backdrop_path': '/rqbCbjB19amtOtFQbb3K2lgm2zv.jpg',
   'genre_ids': [16, 10765, 10759],
   'id': 1429,
   'origin_country': ['JP'],
   'original_language': 'ja',
   'original_name': '進撃の巨人',
   'overview': 'Many years ago, the last remnants of humanity were forced to retreat behind the towering walls of a fortified city to escape the massive, man-eating Titans that roamed the land outside their fortress. Only the heroic members of the Scouting Legion dared to stray beyond the safety of the walls – but even those brave warriors seldom returned alive. Those within the city clung to the illusion of a peaceful existence until the day that dream was shattered, and their slim chance at survival was reduced to one horrifying choice: kill – or be devoured!',
   'popularity': 156.355,
   'poster_path': '/hTP1DtLGFamjfu8WqjnuQdP1n4i.jpg',
   'first_air_date': '2013-04-07',
   'name': 'Attack on Titan',
   'vote_average': 8.658,
   'vote_count': 6275},
  {'adult': False,
   'backdrop_path': '/2w8FaLwwJTWr6ExUMeVgT2Th5YT.jpg',
   'genre_ids': [16, 35, 18, 10759],
   'id': 42705,
   'origin_country': ['JP'],
   'original_language': 'ja',
   'original_name': 'はじめの一歩',
   'overview': "Makunouchi Ippo is an ordinary high school student in Japan. Since he spends most of his time away from school helping his mother run the family business, he doesn't get to enjoy his younger years like most teenagers. Always a target for bullying at school (the family fishing business grants him a distinct odor), Ippo's life is one of hardship. One of these after-school bullying sessions turns Ippo's life around for the better, as he is saved by a boxer named Takamura. He decides to follow in Takamura's footsteps and train to become a boxer, giving his life direction and purpose. Ippo's path to perfecting his pugilistic prowess is just beginning...",
   'popularity': 338.03,
   'poster_path': '/qC4taY6yB9BWJ8IxcbnXR8yUS4o.jpg',
   'first_air_date': '2000-10-03',
   'name': 'Fighting Spirit',
   'vote_average': 8.657,
   'vote_count': 1029},
  {'adult': False,
   'backdrop_path': '/dfmPbyeZZSz3bekeESvMJaH91gS.jpg',
   'genre_ids': [16, 10765, 10759, 18],
   'id': 95557,
   'origin_country': ['US'],
   'original_language': 'en',
   'original_name': 'INVINCIBLE',
   'overview': 'Mark Grayson is a normal teenager except for the fact that his father is the most powerful superhero on the planet. Shortly after his seventeenth birthday, Mark begins to develop powers of his own and enters into his father’s tutelage.',
   'popularity': 232.936,
   'poster_path': '/dMOpdkrDC5dQxqNydgKxXjBKyAc.jpg',
   'first_air_date': '2021-03-25',
   'name': 'INVINCIBLE',
   'vote_average': 8.646,
   'vote_count': 4391},
  {'adult': False,
   'backdrop_path': '/3ILMlmC30QUnYkY3XEBOyJ82Dqu.jpg',
   'genre_ids': [10759, 16, 10765],
   'id': 65930,
   'origin_country': ['JP'],
   'original_language': 'ja',
   'original_name': '僕のヒーローアカデミア',
   'overview': 'A superhero-admiring boy without any powers enrolls in a prestigious hero academy and learns what it really means to be a hero.',
   'popularity': 163.511,
   'poster_path': '/phuYuzqWW9ru8EA3HVjE9W2Rr3M.jpg',
   'first_air_date': '2016-04-03',
   'name': 'My Hero Academia',
   'vote_average': 8.645,
   'vote_count': 4822},
  {'adult': False,
   'backdrop_path': '/3MC8VIxq8u1vKOKTfz6FtrFXuMZ.jpg',
   'genre_ids': [10765, 18, 10759, 9648],
   'id': 135157,
   'origin_country': ['KR'],
   'original_language': 'ko',
   'original_name': '환혼',
   'overview': "A powerful sorceress in a blind woman's body encounters a man from a prestigious family, who wants her help to change his destiny.",
   'popularity': 133.722,
   'poster_path': '/q2IiPRSXPOZ6qVRj36WRAYEQyHs.jpg',
   'first_air_date': '2022-06-18',
   'name': 'Alchemy of Souls',
   'vote_average': 8.646,
   'vote_count': 564},
  {'adult': False,
   'backdrop_path': '/xdTwlG8MYAOkFuAGUqt8LgmgTNZ.jpg',
   'genre_ids': [16, 35, 10765],
   'id': 62741,
   'origin_country': ['JP'],
   'original_language': 'ja',
   'original_name': '神様はじめました',
   'overview': 'Nanami was just a normal high school girl down on her luck until a stranger’s lips marked her as the new Land God and turned her world upside down. Now, she’s figuring out the duties of a deity with the help of Tomoe, a reformed fox demon who reluctantly becomes her familiar in a contract sealed with a kiss. The new responsibilities—and boys—are a lot to handle, like the crow demon masquerading as a gorgeous pop idol and the adorable snake spirit who’s chosen the newly minted god to be his bride. As the headstrong Tomoe tries to whip her into shape, Nanami finds that love just might have cute, pointed fox ears. With romance in the air, will the human deity be able to prove herself worthy of her new title?',
   'popularity': 119.2,
   'poster_path': '/5E7GL8KxpFemEFl3Lv8Fu4RuSwa.jpg',
   'first_air_date': '2012-10-02',
   'name': 'Kamisama Kiss',
   'vote_average': 8.643,
   'vote_count': 868}],
 'total_pages': 102,
 'total_results': 2029}

In [31]:
df = pd.DataFrame(response.json()['results'])[['id','name','overview','popularity','vote_average','vote_count']]
df

,id,name,overview,popularity,vote_average,vote_count
0,1396,Breaking Bad,"Walter White, a New Mexico chemistry teacher, ...",803.550,8.913,14109
1,209867,Frieren: Beyond Journey's End,After the party of heroes defeated the Demon K...,336.506,8.884,262
2,94954,Hazbin Hotel,In attempt to find a non-violent alternative f...,241.966,8.875,1063
3,94605,Arcane,Amid the stark discord of twin cities Piltover...,185.414,8.749,3941
4,246,Avatar: The Last Airbender,"In a war-torn world of elemental magic, a youn...",132.123,8.731,4046
5,37854,One Piece,"Years ago, the fearsome Pirate King, Gol D. Ro...",188.206,8.700,4590
6,31911,Fullmetal Alchemist: Brotherhood,Disregard for alchemy’s laws ripped half of Ed...,316.754,8.698,2006
7,60625,Rick and Morty,Rick is a mentally-unbalanced but scientifical...,569.748,8.697,9628
8,221851,Marry My Husband,"Kang Ji-won, a terminally ill cancer patient, ...",147.348,8.687,393
9,60059,Better Call Saul,Six years before Saul Goodman meets Walter Whi...,1249.211,8.680,5081
10,87108,Chernobyl,The true story of one of the worst man-made ca...,374.107,8.676,6175
11,70785,Anne with an E,"A coming-of-age story about an outsider who, a...",445.068,8.675,4615
12,92685,The Owl House,An animated fantasy-comedy series that follows...,361.153,8.671,1562
13,85937,Demon Slayer: Kimetsu no Yaiba,"It is the Taisho Period in Japan. Tanjiro, a k...",143.924,8.661,6358
14,1429,Attack on Titan,"Many years ago, the last remnants of humanity ...",156.355,8.658,6275
15,42705,Fighting Spirit,Makunouchi Ippo is an ordinary high school stu...,338.030,8.657,1029
16,95557,INVINCIBLE,Mark Grayson is a normal teenager except for t...,232.936,8.646,4391
17,65930,My Hero Academia,A superhero-admiring boy without any powers en...,163.511,8.645,4822
18,135157,Alchemy of Souls,A powerful sorceress in a blind woman's body e...,133.722,8.646,564
19,62741,Kamisama Kiss,Nanami was just a normal high school girl down...,119.200,8.643,868

In [48]:
data = []
for i in range(1,102):
    url = "https://api.themoviedb.org/3/tv/top_rated?language=en-US&page={}".format(i)

    headers = {
        "accept": "application/json",
        "Authorization": "Bearer eyJhbGciOiJIUzI1NiJ9.eyJhdWQiOiIwNzhhY2Y1ZDI0ZTM2ZDBmMDgyMzAyMDVjNGVlMzA0MCIsIm5iZiI6MTcyNTQ0OTk0NC4yOTA1MjQsInN1YiI6IjY2ZDg0NGIwODZmZWMzYWQyODYwNDg5YiIsInNjb3BlcyI6WyJhcGlfcmVhZCJdLCJ2ZXJzaW9uIjoxfQ.dYuKAd731sDkHAJZu-Y1j3eT9OSfSOGf4FbZnfOlk0Q"
    }
    response =  requests.get(url,headers=headers)
    dfs = pd.DataFrame(response.json()['results'])[['id','name','overview','popularity','vote_average','vote_count']]
    data.append(dfs)
    df = pd.concat(data)

In [50]:
df

,id,name,overview,popularity,vote_average,vote_count
0,1396,Breaking Bad,"Walter White, a New Mexico chemistry teacher, ...",803.550,8.913,14109
1,209867,Frieren: Beyond Journey's End,After the party of heroes defeated the Demon K...,336.506,8.884,262
2,94954,Hazbin Hotel,In attempt to find a non-violent alternative f...,241.966,8.875,1063
3,94605,Arcane,Amid the stark discord of twin cities Piltover...,185.414,8.749,3941
4,246,Avatar: The Last Airbender,"In a war-torn world of elemental magic, a youn...",132.123,8.731,4046
...,...,...,...,...,...,...
15,61811,CSI: Cyber,"The FBI's team of Cyber Crime Investigators, h...",94.385,5.972,212
16,37678,The Voice,The strongest vocalists from across the United...,147.207,6.000,200
17,68716,Marvel's Inhumans,After the Royal Family of Inhumans is splinter...,78.478,5.938,674
18,4386,Baywatch,Join the Baywatch lifeguards on their thrillin...,407.313,5.900,458
19,59941,The Tonight Show Starring Jimmy Fallon,After Jay Leno's second retirement from the pr...,1083.624,5.844,310

In [52]:
df.to_csv('movies.csv')

# Web Scrapping

In [2]:
import pandas as pd
import requests
from bs4 import BeautifulSoup

In [4]:
url = 'https://www.ambitionbox.com/list-of-companies?campaign=desktop_nav&page=1'
headers = {
        "User-Agent": "Mozilla/5.0 (Windows NT 6.3; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.3987.162 Safari/537.36"
    }
webpage = requests.get(url,headers=headers).text

In [ ]:
soup = BeautifulSoup(webpage, 'lxml')

In [ ]:
soup.prettify()

In [ ]:
company = soup.find_all('div', class_='company_content_wrapper')
name=[]

for i in company:
    next.append(i.find('h2').text.strip())
    
    
#like this do with all